spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&serverTimezone=PRC&characterEncoding=utf8&useSSL=false
    username: root
    password:
mybatis:
  mapper-locations: classpath:mappers/*.xml